import './globals.css';
import { Inter } from 'next/font/google';
// Importez Head de Next.js

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <>
      
        {/* Définition des métadonnées globales ici */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <title>Océane - Développeuse Web/ Conceptrice - PORTFOLIO</title>
        <meta name="description" content="Portfolio de Océane, développeuse Front End sur Paris" />
        <meta name="keywords" content="développeuse à Paris, Front End, Portfolio, développeur JavaScript, spécialiste React, Océane Verdi, Océane webdev, Océane freelance, Océane développeuse freelance, Océane Verdi développeuse web, Océane Verdi webdev, Océane développeuse web à Paris, Océane développeuse web à 92, Océane Verdi développeuse fronend à Paris, Océane développeuse web 78, Océane développeuse web 93, Océane développeuse web 94, Océane 
        développeuse web 91, Océane développeuse web 95, Océane développeuse web 77, Océane développeuse web à Provins, Océane développeuse web à Versailles, Océane développeuse web à Melun,
        Océane Verdi frontend, Océane développeuse web freelance, Océane développeuse web flexible, Océane développeuse web à Velizy, Océane développeuse web créative, Océane développeuse web bilingue anglais, Océane advocate developer, Océane développeur web multilingue, Océane développeuse web innovante,
        Océane développeuse web en Île-de-France, Océane développeuse web à Chartres, Océane développeuse web à Pontoise, Océane développeuse web à Creteil, Océane développeuse web passionée, Océane Verdi développeuse passionnée, Océane développeuse web en Île-de-France,  
        Développeur Full-Stack, Design graphique, Développement frontend, Développement backend, Création de site web, JavaScript, HTML5, CSS3, React.js, Node.js, Express.js, MongoDB, SQL, 
        PHP, Laravel, Bootstrap, Adobe Photoshop, UI/UX Design, Responsive Design, API Rest, GraphQL, Git et GitHub, Déploiement AWS, Heroku, Firebase, Angular, Vue.js,
        Webpack, NPM, Sass, LESS, Édition d'image, Animation web, Prototypage, Wireframing, A/B Testing, Maintenance de site web, Sécurité web,
        Optimisation SEO, WordPress, CMS personnalisé, eCommerce, Shopify, PrestaShop, Conception de logo, Branding et identité visuelle, Illustration digitale, Intégration web, Développement Agile, Développeur full stack, Conception web responsive,
        Développement frontend, Développement backend, JavaScript avancé, Frameworks React.js, Node.js pour serveur, Express.js, MongoDB, Base de données SQL, Conception d'interfaces utilisateur, Expérience utilisateur UX design, Design graphique web,
        Création de logo personnalisé, Branding digital, Développement d'applications web, Applications single-page (SPA), Programmation CSS avancée, HTML5, SASS et LESS, RESTful APIs, Sécurité web, Optimisation de la performance web, Git et versionning, 
        Déploiement AWS, Hébergement web,  SEO technique, Responsive Design, Animation web CSS3, jQuery, Bootstrap, Material UI, Photoshop pour web design, Illustrator pour designers, Figma pour UI design, Prototypage rapide, Tests unitaires et intégration,
        Automatisation de tests Selenium, Agile et Scrum,  Gestion de projet technique, Consulting en développement web, Intégration continue CI/CD, Docker pour développeurs, Microservices architecture, Développement mobile cross-platform, Flutter pour apps mobiles,
        Web, Code, Design, UX, UI, SEO, Agile, Cloud, Data, Crypto, SaaS, Mobile, React, Node, Python, PHP, Java, SQL, Ruby, Docker, Kubernetes, DevOps, Blockchain, Fintech, Startup, E-commerce,  Marketing, Branding, Analytics, AI (Intelligence Artificielle), VR (Réalité Virtuelle), 
        AR (Réalité Augmentée), IoT (Internet des Objets), CMS, WordPress, Shopify, Magento, Security, Cloudflare, GitHub, Digital, Innovation, Strategy, Growth, Performance, Scalability, Automation, Integration, Accessibility, Sustainability,  Maintenance et support de site web, Création de site web facile, Site internet pour petits commerces, Site web clé en main, Solutions web pour artisans, Lancer sa boutique en ligne, Site web sans code, Site internet personnalisé, Créer une présence en ligne, 
        Site web pour créateurs, Plateforme de vente en ligne, Design de site élégant, Site web pour restaurant, Site internet pour galerie d'art, Création de blog personnel, Site de portfolio en ligne, Services de site web abordables, Refonte de site internet, Conseils pour site web de start-up,
        Site e-commerce pour débutants, Boutique en ligne DIY, Augmenter sa visibilité en ligne, Stratégie digitale pour PME, Gérer facilement son site web, Plateforme intuitive de site web, Solutions digitales pour entrepreneurs, Optimisation de site pour mobile, 
        Atteindre ses clients en ligne,  Site web pour événements et mariages,  Outils en ligne pour indépendants, Site internet sécurisé, Marketing digital simplifié, Visibilité sur Google pour PME, Site web pour artistes, Création de contenu web, Solutions web écologiques, 
        Site internet pour associations, Gestion de contenu facile,  Site web pour éducation et formation,  Services de photographie pour site,  Assistance technique pour site web, Accompagnement projet web, Solutions eCommerce pour petits budgets, Site web pour hébergement touristique,
        Conseils SEO pour débutants, Transformation digitale pour artisans, Site internet pour thérapeutes, Créer un site web multilingue, Optimisation de l'expérience utilisateur, Site web pour fitness et bien-être, Conseil en stratégie digitale personnalisée, Solutions digitales sur mesure,
        Développement d’applications d’entreprise, Transformation digitale pour grandes entreprises, Sécurité informatique avancée, Architecture de systèmes scalables, Gestion de projets IT complexes, Intégration de systèmes d’information, Optimisation de performance web pour entreprises, Services de design UX/UI premium, 
        Consultation en stratégie digitale, Développement Agile pour corporations, Solutions de commerce électronique B2B, Plateformes collaboratives sur mesure, Analyse de données et Business Intelligence, Automatisation des processus d’affaires, Solutions cloud pour entreprises, Développement d’APIs personnalisées, 
        Sécurisation de données et conformité GDPR, Applications mobiles pour le secteur d’entreprise, Refonte de sites web d’entreprise, Optimisation SEO pour le marché B2B, Marketing digital pour professionnels, Création de contenu de marque pour entreprises, Solutions IoT pour l’industrie, Développement de logiciels sur mesure,
        Services de consultation en TI, Infrastructure IT et gestion de réseau,  Développement Salesforce personnalisé, Solutions ERP personnalisées, Intégration de CRM pour grandes entreprises, Plateformes de gestion de contenu d’entreprise, Développement d’applications SaaS, Stratégies de cybersécurité pour entreprises, 
        Solutions de paiement en ligne sécurisées, Développement front-end avancé, Services de back-end pour grandes applications, Audit et amélioration de l’expérience utilisateur, Stratégie de contenu pour engagement B2B, Visualisation de données pour décideurs, Solutions de gestion d’identité et d’accès, Automatisation du marketing pour entreprises,
        Applications web progressives (PWA) pour entreprises, Solutions de réalité augmentée pour le commerce, Développement d'applications blockchain, Conseil en innovation technologique, Optimisation de l’infrastructure cloud, Solutions de gestion des talents digitale, Plateformes de formation en ligne pour entreprises,
        Services de design graphique d’entreprise, Stratégie digitale orientée résultats pour grandes entreprises, Développement web sur mesure, Solutions de commerce électronique, Optimisation de la performance web, Sécurité des applications web, Développement d'applications mobiles, Intégration API pour entreprises, Refonte de site web professionnel,
        Services de développement front-end, Expertise en développement back-end, Conseils en stratégie digitale, Développeur full stack expérimenté, Expert en JavaScript et React, Spécialiste Node.js et Express, Développement d'applications web modernes, Architectures de microservices, Ingénieur logiciel agile,  Conception d'UI/UX innovante, Design graphique pour le web, 
        Solutions de commerce électronique, Optimisation de la performance web, Sécurité des applications web, Développeur mobile cross-platform, Gestion de bases de données SQL et NoSQL, Intégration et déploiement continu (CI/CD), Expert en tests automatisés, Développement d'API RESTful, Connaissance des frameworks frontend modernes, Expérience en développement backend, 
        Projets de développement logiciel sur mesure, Transformation digitale et innovation, Expertise en cloud computing, Programmation orientée objet (POO), Méthodologies de développement Agile et Scrum, Analyse et conception de systèmes, Développement dirigé par les tests (TDD), Responsive web design, Accessibilité web et normes W3C, Développement WordPress personnalisé,
        Maintenance et support technique de site web, Optimisation SEO technique, Automatisation des processus d'affaires, Intelligence artificielle et apprentissage automatique, Visualisation de données et dashboards, Gestion de projet technique, Conseil en technologie et stratégie digitale, Développement d'applications SaaS, Expertise en Git et gestion de versions, Solutions de paiement en ligne et fintech,
        Programmation fonctionnelle, Développement de jeux web, Animation et effets CSS/JavaScript, Expertise en sécurité informatique, Architecture de l'information, Stratégies de contenu web, Développement d'applications PWA (Progressive Web Apps), Big Data et analyse de données, Conception et développement d'interfaces riches, Développement de plateformes collaboratives,
        Virtualisation et conteneurs (Docker, Kubernetes), Projets open source et contribution communautaire, Inspirations de design web moderne, Tutoriels de développement web pour débutants, Projets créatifs en JavaScript, Innovations en UI/UX design, Carrière de développeur full stack, Conseils pour développeurs freelance, Portfolio de design graphique original, Développement d'applications React,
        Travailler avec des startups tech, Créer une app mobile de A à Z, Défis de code et solutions, Meilleures pratiques en sécurité web, Tendances du développement web 2024, Ressources d'apprentissage en développement, Création de contenu digital engageant, Développement de jeux en JavaScript, Automatisation des tâches avec Node.js,  Personal branding pour développeurs, Commencer en développement open source,
        Design interactif et motion design, Développement web responsive, Portfolio digital pour artistes, Conseils pour réussir en tant que designer freelance, Projets DIY en tech et design, Ateliers et webinaires sur le développement web, Stratégies SEO pour portfolios en ligne, Frameworks CSS modernes, Développement d'interfaces riches (Rich UI), Expériences utilisateurs (UX) innovantes,  Graphisme et typographie web, 
        Conseils pour développeurs juniors, Projets GitHub pour débutants, Outils de développement et plugins utiles,  Construire son premier site e-commerce,  Transition de designer à développeur, Animation CSS pour débutants, Développement d'applications avec Vue.js, Stratégies de contenu pour réseaux sociaux, Optimisation de la performance des sites web, Évolution de la carrière en tech, Créer des interfaces utilisateurs avec Figma,
        Projets de contribution à la communauté tech, Conseils de networking pour jeunes professionnels, Gérer des projets tech de bout en bout, Développement d'API RESTful, Éthique et responsabilité en design numérique, Apprentissage machine pour développeurs web, Créativité et technologie, Développer avec des technologies émergentes, Leadership et management dans la tech,
        Leadership et management dans la tech, Lancer son business en ligne facilement, Solutions web pour startups féminines, Site internet clé en main pour entrepreneures, Plateforme e-commerce intuitive, Design web élégant pour petites entreprises, Conseils en stratégie digitale pour femmes, Développement de site personnalisé pour PME, Boutique en ligne simple pour créatrices, Augmenter sa visibilité en ligne,
        Outils web faciles pour entrepreneures,  Créer une marque en ligne impactante, Services de site web abordables pour startups, Web design inspirant pour femmes d'affaires, Gestion de contenu simplifiée, Optimisation SEO pour débutantes, Stratégies digitales pour le marché féminin, Ateliers de création de site pour non-tech, Identité visuelle pour marques féminines, Site web responsive pour mobile,  Conseils marketing en ligne pour startups,
        Refonte de site pour moderniser votre image, Intégration de réseaux sociaux pour engagement, Solutions de paiement en ligne sécurisées, Accompagnement projet web de A à Z, Formation en gestion de site pour entrepreneures, Création de contenu web ciblé, Assistance technique pour site web, Site internet éco-responsable, Plateforme de services pour femmes, Blogs professionnels pour entrepreneures, Création de communauté en ligne, Branding et storytelling pour startups,
        Site web multilingue pour expansion internationale, Outils d'analyse web pour suivre le succès, Conseils pour choisir sa plateforme e-commerce, Créer une expérience utilisateur inoubliable, Sécurité site web pour entrepreneurs, Développement durable et site web, Stratégie de contenu pour attirer clients, Optimisation de l'expérience client en ligne, Conseils en ligne pour entrepreneurs débutants,Tendances web design pour startups, Créer un site web inclusif, 
        Automatisation pour faciliter la gestion, Techniques de vente en ligne efficaces, Créer un portfolio en ligne, Améliorer la conversion de site web, Étude de marché digitale pour startups, Création de site web axée résultats, Création de site web pour avocats, Solutions web pour cabinets d'avocats, Site internet professionnel pour juristes, Design web pour professions juridiques, Développement de site pour avocats, Optimisation SEO pour le droit, Marketing digital pour avocats,
        Gestion de contenu pour sites juridiques, Plateforme en ligne pour services juridiques, Stratégie digitale pour le secteur légal, Stratégie digitale pour le secteur légal, Présence en ligne pour experts juridiques, Portfolio en ligne pour avocats, Blog juridique et création de contenu, Solutions eCommerce pour services légaux, Design UX/UI pour sites d'avocats, Automatisation pour cabinets d'avocats, Intégration de système de rendez-vous en ligne, Site web responsive pour le droit, 
        Refonte de site pour professionnels du droit, Visibilité en ligne pour avocats, Conseils SEO pour sites juridiques, Marque personnelle pour avocats, Développement WordPress pour sites légaux, Sites web multilingues pour le droit, Création de logo pour cabinets d'avocats,  Photographie professionnelle pour sites juridiques, Vidéo de présentation pour avocats, Système de gestion de cas en ligne, Outils en ligne pour la consultation juridique, Services de traduction pour sites d'avocats, 
        Protection de la vie privée et sécurité web, Solutions de paiement en ligne pour services légaux, Optimisation mobile pour sites d'avocats, Intégration de réseaux sociaux pour le droit, Publicité en ligne pour cabinets d'avocats, Génération de leads pour services juridiques, Témoignages et études de cas pour avocats, Analyse de performance pour sites légaux, Conseils en stratégie de contenu juridique, Accessibilité web pour sites d'avocats, Email marketing pour professionnels du droit,  
        Campagnes PPC pour avocats, Branding et identité visuelle pour le droit, Maintenance et support pour sites juridiques, Formation web pour avocats, Solutions cloud pour cabinets d'avocats, Archivage et gestion documentaire en ligne, Conformité RGPD pour sites d'avocats, Référencement local pour cabinets juridiques, Création de site pour médecins, Site web pour cabinets médicaux, Développement web pour kinésithérapeutes,  Solutions web pour professionnels de santé, Site internet pour cliniques privées, 
        Web design pour services de santé, Optimisation SEO pour praticiens médicaux, Marketing digital pour professionnels de la santé, Plateforme en ligne pour rendez-vous médicaux, Gestion patient en ligne, Application mobile pour cabinet médical, Site web informatif pour patients, Design web pour dentistes, Création de contenu pour sites de santé, Site personnalisé pour infirmières, Portfolio numérique pour chirurgiens, SEO pour spécialistes médicaux, Solutions digitales pour pharmacies,
        Interface patient-praticien en ligne, Site de conseil en santé, E-commerce pour matériel médical, Blog professionnel pour médecins, Réseaux sociaux pour cliniques, Présence en ligne pour services d'urgence, Plateforme éducative pour patients, Site de réservation pour consultations, Identité visuelle pour professionnels de santé, Campagnes AdWords pour cabinets médicaux, Gestion de la réputation en ligne pour médecins, Solutions de téléconsultation web, Site web bilingue pour praticiens, 
        Intégration de système de paiement en ligne, Sécurité des données patient sur le web, Accessibilité web pour sites de santé, Conseils en nutrition en ligne, Services de psychologie en ligne, Plateformes de suivi de traitement, Blogs spécialisés en soins infirmiers, Sites web pour associations médicales, Marketing de contenu pour la santé, Création de site pour thérapeutes, Développement de site pour laboratoires, Stratégies SEO pour la santé mentale, Web design pour la médecine alternative, 
        Sites éducatifs pour prévention santé, Portails pour gestion de santé à domicile, Création de communauté en ligne pour patients, Plateformes de conseils en santé publique, Sites de recrutement pour professionnels de santé, Création de site pour chirurgiens plastiques, Marketing digital pour centres esthétiques, Site web pour masseurs professionnels, Solutions web pour soins esthétiques, SEO pour cliniques de chirurgie plastique, Design de site pour spas et bien-être, Plateforme de réservation en ligne pour massages,
        Web design pour esthéticiennes, Développement de site pour salons de beauté, Optimisation de site pour médecine esthétique, Site internet pour services de cosmétologie, Marketing en ligne pour soins du visage, Présence web pour thérapeutes corporels, Solutions digitales pour soins anti-âge, Blog professionnel pour conseils beauté, E-commerce pour produits de beauté professionnels, Plateforme de consultation pour chirurgie esthétique, Stratégies SEO pour masseurs, Site personnalisé pour instituts de beauté, 
        Référencement web pour dermatologues esthétiques, Campagnes publicitaires pour liposuccion, Site de portfolio pour artistes du maquillage, Gestion de la réputation en ligne pour chirurgiens, Conseils en ligne pour soins de la peau, Services de branding pour cliniques esthétiques, Plateformes de réservation pour soins corporels, Site web multilingue pour tourisme médical, Sécurité et confidentialité pour patients en ligne, Blogs spécialisés en tendances esthétiques, Blogs spécialisés en tendances esthétiques, 
        Interface utilisateur intuitive pour sites de bien-être, Campagnes SEO pour augmentation mammaire, Solutions web pour gestion de spa, Systèmes de paiement en ligne pour services de beauté, Applications mobiles pour conseils beauté, Marketing de contenu pour chirurgie reconstructive, Réseaux sociaux pour promotion de services esthétiques, Optimisation mobile pour sites de bien-être, Publicités en ligne pour traitement anti-cellulite, Site web pour consultation de rhinoplastie, Plateforme éducative pour chirurgie plastique, 
        Stratégies de contenu pour soins faciaux, Campagnes AdWords pour esthéticiens, Site internet pour techniciens en laser esthétique, Marketing en ligne pour rajeunissement de la peau, Solutions digitales pour cours de maquillage, SEO local pour salons de manucure, Web design pour centres de remise en forme, Blogs sur la santé et la beauté, Campagnes de publicité pour peelings chimiques, Optimisation de présence en ligne pour lifting facial, Création de boutique en ligne pour influenceurs,
        Site web pour marques de créateurs, Solutions eCommerce pour personnalités du web, Design de site pour créateurs de mode, Plateforme de vente pour artistes, Optimisation SEO pour boutiques d'influenceurs, Marketing digital pour influenceurs, Stratégie de marque pour créateurs de contenu, Boutique en ligne personnalisée, Web design pour influenceurs de beauté, Création de contenu pour sites de mode, Gestion de marque personnelle en ligne, Solutions de paiement pour boutiques en ligne, Photographie de produit pour eCommerce,
        Site web pour lancements de produits, Conseils en marketing d'affiliation,  SEO pour boutiques de créateurs,  Réseaux sociaux et intégration web, Plateformes de cours en ligne pour influenceurs, Blogs de lifestyle et design web, Gestion des réseaux sociaux pour marques personnelles, Publicité en ligne pour produits d'influenceurs, Boutique Shopify pour créateurs, Identité visuelle pour influenceurs, Stratégies de contenu pour boutiques en ligne, Campagnes AdWords pour produits de créateurs, Site web multilingue pour audience globale, 
        Analyses et optimisation de la conversion web, Intégration de critiques et avis clients, Newsletters et gestion d'email marketing, Création de communauté en ligne, Landing pages pour lancements exclusifs, Stratégies de vente croisée et montée en gamme, Tutoriels et contenus éducatifs pour fans, Gestion de portfolio pour influenceurs, Sécurité en ligne et protection de la marque, Solutions logistiques pour boutiques en ligne, Conseils pour le développement de produits, Collaboration et partenariats de marque, Vidéos promotionnelles pour sites web,
        Intégration de flux Instagram sur le site,  Plateformes de podcast pour influenceurs, Engagement des fans et interactions en ligne, Widgets et plugins pour améliorer l'expérience utilisateur, Solutions de fidélisation pour clients en ligne, Analyse de tendances pour produits de niche, Conseils pour améliorer la visibilité en ligne, Techniques de storytelling pour marques personnelles, Planification d'événements virtuels, Stratégies de contenu cross-platform, 
        Création de site pour artistes du spectacle, Marketing digital pour performers, Site web sécurisé pour artistes, Solutions de paiement en ligne pour spectacles, Plateforme de streaming pour performances, Design web pour professionnels du divertissement,  Gestion de la présence en ligne pour artistes, Optimisation SEO pour spectacles adultes, Boutique en ligne pour produits de spectacle, Services de photographie professionnelle pour artistes, Branding personnel pour performers, Création de contenu visuel pour artistes, Stratégies de réseaux sociaux pour spectacles, 
        Solutions de merchandising pour artistes,  Conseils en gestion de carrière pour performers, Développement de marque pour artistes indépendants, Protection de la vie privée en ligne pour artistes, Conseils en droits d'auteur pour spectacles, Site web pour booking d'artistes, Gestion de communauté en ligne pour fans, Plateforme de vente de tickets en ligne, Conseils juridiques pour artistes du spectacle, Stratégies de monétisation pour performances en ligne, Services de vidéo à la demande pour spectacles, Campagnes de publicité ciblée pour événements, 
        Solutions web pour la gestion d'événements, Conseils en image de marque pour artistes, Services de relations publiques pour spectacles, Plateforme de critiques et de recommandations de spectacles, Création de portfolio en ligne pour artistes, Développement de sites web multilingues pour artistes, Optimisation pour moteurs de recherche spécialisés, Référencement local pour artistes et spectacles,  Services de coaching en ligne pour artistes, Solutions eCommerce pour produits dérivés d'artistes, Sites web pour galeries d'art virtuelles, 
        Gestion des droits numériques pour contenus d'artistes, Plateformes de diffusion en direct pour événements, Création d'applications mobiles pour fans, Stratégies de contenu pour engagement de la communauté, Sécurité des transactions en ligne pour achats de billets, Sites web adaptatifs pour tous les appareils, Optimisation de la vitesse de chargement de site, Analyse de trafic web pour optimisation, Création d'événements exclusifs en ligne pour fans, Solutions de gestion d'abonnements pour contenus, Création de blogs professionnels pour artistes, 
        Conseils en développement personnel pour performers, Marketing d'influence pour promotions d'événements, Conseils en nutrition et bien-être pour artistes, Site web pour photographes, Portfolio numérique pour photographes, Solutions web pour photographie, Création de site pour studios photo, Galeries en ligne pour photographes, Optimisation SEO pour photographes, Site web responsive pour photographie, Développement de boutique en ligne photo, Marketing digital pour photographes, Services de web design pour photographie, Intégration e-commerce pour ventes de photos,
        Site personnalisé pour photographes professionnels, Gestion de contenu pour sites de photographie, Amélioration de site web pour photographes, Plateformes de partage de photos, SEO pour studios de photographie, Création de blog pour photographes, Solutions de réservation en ligne pour sessions photo, Design web élégant pour photographie, Sites web pour photographie de mariage, Refonte de site pour photographes, Stratégies de visibilité en ligne pour photographie, Sites web pour photographie de nature, Solutions digitales pour photographie d'événements, 
        Plateforme de gestion de portfolio photo, Optimisation de la vitesse du site photo, Sécurité en ligne pour galeries photo, Services de retouche photo en ligne, Conseils en marketing pour photographes, Intégration de fonctionnalités de partage social, Sites web pour photographie de mode, Création de contenu visuel pour photographes, Plateformes éducatives pour cours de photographie, Solutions de paiement en ligne pour photographes, Développement de site pour photographie culinaire, Sites web pour photographie sportive, SEO local pour photographes indépendants,
        Galeries virtuelles pour expositions photo, Site web multilingue pour photographes internationaux, Solutions web pour photographie de produits, Analyse de performance de site pour photographes, Plateforme de témoignages clients pour photographes, Création de site pour photographie immobilière, Optimisation mobile pour sites de photographie, Stratégies de contenu pour blogs de photographie, Campagnes publicitaires en ligne pour photographes, Services de branding pour photographes, Sites web pour photographie animalière, Solutions de stockage en ligne pour archives photo, 
        Développement de fonctionnalités de recherche d'images avancées, Site web tourisme France, Développement site culture française, Création site gastronomie française, Web design mode Paris, Services web pour hôtels en France, Plateforme e-commerce produits français, Site vitrine artisanat français, SEO pour sites de tourisme en France, Blog voyage Paris, Site événementiel festivals français, Galerie en ligne art français, Boutique en ligne vins français, Plateforme réservation restaurants Paris, Site éducatif langue française, Développement web écoles de cuisine en France,
        E-boutique mode française,  Web design pour agences de voyage spécialisées France, Plateforme streaming musique française,  Site web pour expatriés en France, Création de contenu culturel français, Services web pour guides touristiques France, Site portfolio pour artistes français,  Développement site pour marques françaises,  Solutions web pour événements culturels français, Création de communauté en ligne francophiles, Site web pour apprendre la cuisine française, Portfolio numérique photographie française, Site de critique cinéma français, Boutique cadeaux souvenirs de France, 
        Plateforme de cours en ligne sur la France, Blog mode de vie à la française,  Site pour amateurs de fromage français, Développement web pour festivals de film français, E-commerce cosmétiques français, Site de conseils voyage en France, Plateforme de partage recettes françaises, Web design pour librairies françaises, Site pour collectionneurs d'art français, Solutions web pour marchés de Noël en France,  SEO pour établissements d'enseignement français, Plateforme pour étudiants internationaux en France, Blog expériences culinaires françaises, Site web histoire et patrimoine français, 
        E-boutique bijoux fabriqués en France, Plateforme pour cours de français en ligne, Développement d'applications mobiles tourisme France, Site de réservation pour châteaux français, Web design pour entreprises françaises à l'international, Marketing digital pour produits de luxe français, Solutions web pour expériences touristiques uniques en France,  " />
       


        <link rel="icon" href="favicon.ico" />
        
        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.oceane-developpeuse.info/" />
        <meta property="og:title" content="Océane - Portfolio" />
        <meta property="og:description" content="Portfolio de Océane, développeuse Front End sur Paris" />
        <meta property="og:image" content="/public/images/Moi.webp" />
        
        {/* Twitter */}
        <meta property="twitter:card" content="Portfolio" />
        <meta property="twitter:url" content="https://www.oceane-developpeuse.info/" />
        <meta property="twitter:title" content="Océane - Portfolio" />
        <meta property="twitter:description" content="Portfolio de Océane, développeuse Front End sur Paris" />
        <meta property="twitter:image" content="/public/images/Moi.webp" />
        
        {/* Ajoutez ici d'autres métadonnées si nécessaire */}
    
      {/* La structure principale de votre page */}
      <html lang="fr">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
